name: flutter_show_more
description: Flutter widget for limiting the amount of text to show.
version: 1.0.1
repository: https://github.com/jajpa/flutter_show_more
homepage: https://joshuamatta.dev
topics:
  - flutter
  - text
  - show-more
  - widget

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
